### PR TITLE
Allow use with Laravel 9

### PR DESCRIPTION
**Pull request by dcodegroup**
Allow use with Laravel 9

### CODE REVIEW

**Comment by lionslair** [comment]
> Hey there, any reason why the composer.lock has been removed altogether instead of just updating it? Have you run the automatic tests to check if everything is working fine?

Do you mean the ones in the package?
`
─nathanr@pop-os ~/Code/vendor-packages/laravel-cloudfront-url-signer ‹master●› 
╰─$ phpunit                   
PHPUnit 9.5.13 #StandWithUkraine

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

......                                                              6 / 6 (100%)

Time: 00:00.054, Memory: 16.00 MB

OK (6 tests, 7 assertions)
`

Yes.

I never commit the composer.lock file for packages. https://github.com/dcodegroup?tab=repositories

I follow the spatie approach where they don't either. I rarely see it committed due to them being locked to versions. If you need to lock a version lock it in composer.json.

eg
https://github.com/spatie/laravel-permission
https://github.com/spatie/laravel-medialibrary
https://github.com/spatie/laravel-log-dumper

**Comment by IlCallo** [comment]
> I rarely see it committed due to them being locked to versions. If you need to lock a version lock it in composer.json.

IMO that's the exact reason to have them committed, otherwise every dev downloading the package may end up with a broken environment, in case something went wrong upstream.
Pinning dependencies into composer.json, on the other side, could create problems when the package is used downstream.

Could you regenerate the composer.lock and re-commit it?

**Comment by lionslair** [comment]
> > I rarely see it committed due to them being locked to versions. If you need to lock a version lock it in composer.json.
> 
> IMO that's the exact reason to have them committed, otherwise every dev downloading the package may end up with a broken environment, in case something went wrong upstream. Pinning dependencies into composer.json, on the other side, could create problems when the package is used downstream.
> 
> Could you regenerate the composer.lock and re-commit it?

Done

**Comment by IlCallo** [comment]
Released as 3.3.0, thanks for taking the time to create a PR :)

**Pull request merged**
