### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:information_source: Shift detected you do not have a CI workflow using GitHub Actions. If you would like, Shift can help you get started with the [CI Generator](https://laravelshift.com/ci-generator). Although the Shift is paid, GitHub Actions is free and having a CI workflow will improve the stability and review process for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-cloudfront-url-signer.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "dreamonkey/laravel-cloudfront-url-signer": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by wwright216** [comment]
Bump. @IlCallo Can we get this merged in 🙏

**Comment by Shokushu** [comment]
+1

**Comment by IlCallo** [comment]
Hey there, we don't currently have time to manage this, we'll test and merge this as time permits

**Comment by Shokushu** [comment]
Do you have a rough ETA? @IlCallo

**Comment by IlCallo** [comment]
Hey, probably by the end of this month, we just completed a couple projects and we're slowly catching up with the backlog

**Comment by Shokushu** [comment]
Thanks for the update! ❤️

**Comment by wwright216** [comment]
@IlCallo We're past the end of May 😞

**Comment by mohsinsiyal-tsi** [comment]
What is the estimated date for merging this?

**Comment by IlCallo** [comment]
I'm sorry, but the backlog to catch up was apparently bigger than expected, and some of us had some health issues 😅 
I'll try to check this out soon

**Comment by mpryvkin** [comment]
+1

**Comment by IlCallo** [comment]
Ok, apparently my Homestead setup eventually corrupted itself
I'm gonna merge this without testing it first

We're also gonna mark this repository as unmaintained right after, as we don't have time anymore to manage and maintain these Laravel packages

If someone wants to take the lead and publish a fork, we can link to its package

**Pull request merged**
