### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by aleahy**
Just adding support to use with PHP 8.
Tests all run fine.

### CODE REVIEW

**Comment by billowapp** [comment]
Any news on this PR?

**Comment by IlCallo** [comment]
I'm a bit swamped and don't have much time to try this out. Can someone else double-check tests actually run fine on PHP8?
@billowapp

**Comment by billowapp** [comment]
Hey IlCallo, thanks for your response here. I can confirm that is working. I ended up having to fork the repo to get it installed into a production app. But like i say it's definitely working.

**Comment by billowapp** [comment]
Herewith the test output.

Screenshot 2021-04-08 at 14 57 04

**Pull request merged**
